const tree = {
    name: 'PCAS LEWIS3',
    description: null,
    qty: 0,
    children: [
        {
            name: 'SEKRIT BITS',
            description: 'BITS KIT FOR LS6000 SEKRIT LOUDSPEAKER ',
            qty: 1,
            children: [
                {
                    name: '1F-137',
                    description: '3MM ALLEN KEYS',
                    qty: 1,
                    children: null,
                    type: 'C',
                    parentName: 'SEKRIT BITS',
                    id: '40172',
                    hasChanged: null,
                    changeState: 'LIVE',
                    addChangeDocumentNumber: 3845,
                    isReplaced: false,
                    replacementFor: null,
                    replacedBy: null,
                    addReplaceSeq: null,
                    deleteReplaceSeq: null,
                    toDelete: null,
                    requirement: 'Y',
                    drawingReference: null,
                    safetyCritical: 'N'
                },
                {
                    name: '2S-625',
                    description: 'MINIGRIP BAG SIZE 4 X 5 1/2',
                    qty: 1,
                    children: null,
                    type: 'C',
                    parentName: 'SEKRIT BITS',
                    id: '40173',
                    hasChanged: null,
                    changeState: 'LIVE',
                    addChangeDocumentNumber: 3845,
                    isReplaced: false,
                    replacementFor: null,
                    replacedBy: null,
                    addReplaceSeq: null,
                    deleteReplaceSeq: null,
                    toDelete: null,
                    requirement: 'Y',
                    drawingReference: null,
                    safetyCritical: 'N'
                },
                {
                    name: 'MCP 826',
                    description: 'CABLE CLAMP FOR SEKRIT IN WALL LOUDSPEAKER',
                    qty: 2,
                    children: null,
                    type: 'C',
                    parentName: 'SEKRIT BITS',
                    id: '40178',
                    hasChanged: null,
                    changeState: 'LIVE',
                    addChangeDocumentNumber: 3845,
                    isReplaced: false,
                    replacementFor: null,
                    replacedBy: null,
                    addReplaceSeq: null,
                    deleteReplaceSeq: null,
                    toDelete: null,
                    requirement: 'Y',
                    drawingReference: 'MCP 826 REV 0',
                    safetyCritical: 'N'
                },
                {
                    name: 'MCP 848',
                    description: 'ALUMINIUM RETAINING TAB FOR SEKRITIN WALL SPEAKER',
                    qty: 16,
                    children: null,
                    type: 'C',
                    parentName: 'SEKRIT BITS',
                    id: '46621',
                    hasChanged: null,
                    changeState: 'LIVE',
                    addChangeDocumentNumber: 4473,
                    isReplaced: false,
                    replacementFor: null,
                    replacedBy: null,
                    addReplaceSeq: null,
                    deleteReplaceSeq: null,
                    toDelete: null,
                    requirement: 'Y',
                    drawingReference: 'MCP 848 REV 0',
                    safetyCritical: 'N'
                },
                {
                    name: 'MECH 010',
                    description: 'M4 INT. S.PROOF WASHERS ZINC & BLACK PASS',
                    qty: 2,
                    children: null,
                    type: 'C',
                    parentName: 'SEKRIT BITS',
                    id: '40174',
                    hasChanged: null,
                    changeState: 'LIVE',
                    addChangeDocumentNumber: 3845,
                    isReplaced: false,
                    replacementFor: null,
                    replacedBy: null,
                    addReplaceSeq: null,
                    deleteReplaceSeq: null,
                    toDelete: null,
                    requirement: 'Y',
                    drawingReference: null,
                    safetyCritical: 'N'
                },
                {
                    name: 'MECH 055',
                    description: 'M4 X 10 SOCKET HEX HEAD CAP SCREW NICKEL PLATED',
                    qty: 2,
                    children: null,
                    type: 'C',
                    parentName: 'SEKRIT BITS',
                    id: '40175',
                    hasChanged: null,
                    changeState: 'LIVE',
                    addChangeDocumentNumber: 3845,
                    isReplaced: false,
                    replacementFor: null,
                    replacedBy: null,
                    addReplaceSeq: null,
                    deleteReplaceSeq: null,
                    toDelete: null,
                    requirement: 'Y',
                    drawingReference: null,
                    safetyCritical: 'N'
                },
                {
                    name: 'MECH 185',
                    description:
                        'M4 X 40 CAP SCREW (FULLY THREADED ZINC AND BLACK PASSIVATED FINISH).',
                    qty: 18,
                    children: null,
                    type: 'C',
                    parentName: 'SEKRIT BITS',
                    id: '176091',
                    hasChanged: null,
                    changeState: 'LIVE',
                    addChangeDocumentNumber: 21041,
                    isReplaced: false,
                    replacementFor: null,
                    replacedBy: null,
                    addReplaceSeq: null,
                    deleteReplaceSeq: null,
                    toDelete: null,
                    requirement: 'Y',
                    drawingReference: null,
                    safetyCritical: 'N'
                },
                {
                    name: 'SCRW 019',
                    description: 'M4 X 20 SOCKET CAP SCREW (ZB NON UK MANUF)',
                    qty: 4,
                    children: null,
                    type: 'C',
                    parentName: 'SEKRIT BITS',
                    id: '48284',
                    hasChanged: null,
                    changeState: 'LIVE',
                    addChangeDocumentNumber: 4855,
                    isReplaced: false,
                    replacementFor: null,
                    replacedBy: null,
                    addReplaceSeq: null,
                    deleteReplaceSeq: null,
                    toDelete: null,
                    requirement: 'Y',
                    drawingReference: null,
                    safetyCritical: 'N'
                }
            ],
            type: 'A',
            parentName: null,
            id: 'lcuiyjioi8lz6yldm5g',
            hasChanged: null,
            changeState: 'PROPOS',
            addChangeDocumentNumber: 0,
            isReplaced: false,
            replacementFor: null,
            replacedBy: null,
            addReplaceSeq: null,
            deleteReplaceSeq: null,
            toDelete: null,
            requirement: null,
            drawingReference: null,
            safetyCritical: null
        },
        {
            name: 'CAP 530',
            description: '68PF,,,,,TH,,,,,,',
            qty: 1,
            children: null,
            type: 'C',
            parentName: null,
            id: 'lcuj17b7gra0ixpitad',
            hasChanged: null,
            changeState: 'PROPOS',
            addChangeDocumentNumber: 0,
            isReplaced: false,
            replacementFor: null,
            replacedBy: null,
            addReplaceSeq: null,
            deleteReplaceSeq: null,
            toDelete: null,
            requirement: null,
            drawingReference: null,
            safetyCritical: null
        }
    ],
    type: null,
    parentName: null,
    id: 'root',
    hasChanged: true,
    changeState: null,
    addChangeDocumentNumber: 0,
    isReplaced: false,
    replacementFor: null,
    replacedBy: null,
    addReplaceSeq: null,
    deleteReplaceSeq: null,
    toDelete: null,
    requirement: null,
    drawingReference: null,
    safetyCritical: null
};

export default tree;
