namespace Linn.Purchasing.Domain.LinnApps.PurchaseOrders
{
    using System;

    public class CancelledPODetail
    {
        //ORDER_NUMBER NOT NULL NUMBER
        //PLOC_ID NOT NULL NUMBER(6)
        //ORDER_LINE NUMBER(6)
        //DELIVERY_SEQ NUMBER(6)
        //DATE_ORDER_CANCELLED DATE
        //ORDER_CANCELLED_BY NUMBER(6)
        //DATE_FIL_CANCELLED DATE
        //FIL_CANCELLED_BY NUMBER(6)
        //REASON_CANCELLED NOT NULL VARCHAR2(600)
        //PERIOD_CANCELLED NUMBER
        //PERIOD_FIL_CANCELLED NUMBER
        //VALUE_CANCELLED NUMBER(14,2)
        //DATE_UNCANCELLED DATE
        //DATE_UNFIL_CANCELLED DATE
        //DATE_PREVIOUSLY_CANCELLED DATE
        //DATE_PREVIOUSLY_FIL_CANCELLED DATE
        //VALUE_FIL_CANCELLED NUMBER(14,2)
        //BASE_VALUE_FIL_CANCELLED NUMBER(14,2)
    }
}
